### ISSUE TITLE
`justify-content` needs further explanation

### ISSUE THREAD

**Issue by stefankp** [channingallen/tower-defense#6]
Great job on the instructional game, I really like it!

However, it's important to understand how `justify-content` really works. Your explanation for the first wave states `justify-content positions a container's items horizontally [...]`, which is not entirely correct. This is only true, as long as the main-axis is the horizontal axis, meaning `flex-direction: row` or `flex-direction: row-reverse`. Changing `flex-direction` to `column` also changes the main-axis and therefore the `justify-content` (and `align-items`) behavior. 

Would be great to add a level wich teaches that differentiation. 

> The CSS justify-content property defines how the browser distributes space between and around flex items along the main-axis of their container. (https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content)

> The flex-direction CSS property specifies how flex items are placed in the flex container defining the main axis and the direction (normal or reversed). (https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction)

**Comment by channingallen** [comment]
Good input stefankp. I'll fix these descriptions soon.

**Comment by channingallen** [comment]
I just put up a better explanation — complete with a diagram! Thanks for the heads up @stefankp.

**Comment by stefankp** [comment]
@channingallen Great :+1:
